---
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@v4

      - name: setup@python
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12

      - name: setup@deps
        run: pdm install

      - name: run@tests
        run: pdm run pytest
        env:
          PYTEST_NETBOX_PLUGIN_NETBOX_START_PERIOD: 300
